"""
Scan tuning constants and mode identifiers.
"""

RAW_READ_CHUNK_SIZE = 1024 * 1024
FILESYSTEM_SCAN_INTERVAL = 0.25
CARVE_SCAN_INTERVAL = 0.15
PROGRESS_MIN_INTERVAL = 0.25
ETA_UPDATE_INTERVAL = 5.0
IMAGE_READ_CHUNK_SIZE = 4 * 1024 * 1024

SCAN_MODE_AUTO = "auto"
SCAN_MODE_FILESYSTEM = "filesystem"
SCAN_MODE_DEEP_CARVE = "deep_carve"
SCAN_MODE_QUICK_CARVE = "quick_carve"
SCAN_MODE_EXT4_DELETED = "ext4_deleted"
SCAN_MODE_FREE_SPACE = "free_space"

ALL_SCAN_MODES = [
    SCAN_MODE_AUTO,
    SCAN_MODE_FILESYSTEM,
    SCAN_MODE_EXT4_DELETED,
    SCAN_MODE_FREE_SPACE,
    SCAN_MODE_DEEP_CARVE,
    SCAN_MODE_QUICK_CARVE,
]
