"""
Scan tuning constants and mode identifiers.
"""

RAW_READ_CHUNK_SIZE = 1024 * 1024
FILESYSTEM_SCAN_INTERVAL = 0.25
CARVE_SCAN_INTERVAL = 0.15
PROGRESS_MIN_INTERVAL = 0.25
ETA_UPDATE_INTERVAL = 5.0
IMAGE_READ_CHUNK_SIZE = 4 * 1024 * 1024
IMAGE_SECTOR_FALLBACK_SIZE = 512
IMAGE_CHECKPOINT_INTERVAL_SECONDS = 5.0
DEVICE_READ_TIMEOUT_SECONDS = 15.0
IMAGE_SECTOR_TIMEOUT_SECONDS = 1.0

SCAN_MODE_AUTO = "auto"
SCAN_MODE_FILESYSTEM = "filesystem"
SCAN_MODE_DEEP_CARVE = "deep_carve"
SCAN_MODE_QUICK_CARVE = "quick_carve"
SCAN_MODE_EXT4_DELETED = "ext4_deleted"
SCAN_MODE_FREE_SPACE = "free_space"
SCAN_MODE_FAT32_DELETED = "fat32_deleted"
SCAN_MODE_NTFS_DELETED = "ntfs_deleted"
SCAN_MODE_EXFAT_DELETED = "exfat_deleted"

ALL_SCAN_MODES = [
    SCAN_MODE_AUTO,
    SCAN_MODE_FILESYSTEM,
    SCAN_MODE_EXT4_DELETED,
    SCAN_MODE_FAT32_DELETED,
    SCAN_MODE_NTFS_DELETED,
    SCAN_MODE_EXFAT_DELETED,
    SCAN_MODE_FREE_SPACE,
    SCAN_MODE_DEEP_CARVE,
    SCAN_MODE_QUICK_CARVE,
]
